---
title: "Jornada Bahada Site Data Check: Flux Table"
author: "Marguerite Mauritz"
output: flexdashboard::flex_dashboard
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# load required libraries
library(flexdashboard)
library(data.table)
library(ggplot2)
library(gridExtra)
library(lubridate)
library(plotly)

# ENTER YEAR TO CHECK HERE
yeartocheck <- 2022

# get windrose function, source directly from Github
#source("~/Desktop/R/R_programs/Functions/plot.windrose.R")
source(paste0("https://raw.githubusercontent.com/MargueriteM/R_functions/master/plot.windrose.R"))

# import data directly from SEL Data Archive
flux_colnames <- fread(paste("/Volumes/SEL_Data_Archive/Research Data/Desert/Jornada/Bahada/Tower/Flux/",yeartocheck,"/Raw_Data/ASCII/dataL1_flux_",yeartocheck,".csv",sep=""),
                  header = TRUE, skip=1,sep=",", fill=TRUE,
                 na.strings=c(-9999,"#NAME?"))[1,]

flux <- fread(paste("/Volumes/SEL_Data_Archive/Research Data/Desert/Jornada/Bahada/Tower/Flux/",yeartocheck,"/Raw_Data/ASCII/dataL1_flux_",yeartocheck,".csv",sep=""),
                  header = FALSE, skip=4, sep=",", fill=TRUE,
                 na.strings=c(-9999,"#NAME?"),
              col.names=colnames(flux_colnames))

# convert the time stamp to a posixct format
flux[,date_time := parse_date_time(TIMESTAMP, c("%Y!-%m-%d %H:%M:%S",
                                                    "%m-%d-%y %H:%M"))]

# create derivative date columns
flux[,':=' (year = year(date_time), doy = yday(date_time), date = date(date_time))]

# calculate CO2 ppm from CO2_mean (mg/m^3) 
# https://www.teesing.com/en/page/library/tools/ppm-mg3-converter
flux[,CO2_ppm := (CO2_mean/0.0409)/44.01]

```
# Plot Tower Flux and Met Data

Column {.sidebar}
---------------------------------------

###Select Date Range and variables

These graphs show most recent incoming eddy covariance and ancillary data from the tower at the Jornada Bahada Site. Data are 30min mean values.

**Note: Flux calculations are preliminary and for visualisation only!!** 

#### Last timestamp when data sent to server:

```{r, echo=FALSE, warning=FALSE, message=FALSE}

print(max(flux$TIMESTAMP))
```


```{r, echo=FALSE, warning=FALSE, message=FALSE}

dateRangeInput("daterange", "Date range:",
                 start = min(flux$date),
                 end   = max(flux$date),
                 min = min(flux$date),
                 max = max(flux$date))

radioButtons("variable1", "Flux variables:",
             c("CO2 Flux WPL (mg/m2/sec)" = "Fc_wpl",
               "CO2 mean concentration (mg/m3)" = "CO2_mean",
               "CO2 mean ppm" = "CO2_ppm",
               "Sensible Heat WPL (W/m2)" = "Hc",
               "Latent Heat WPL (W/m2)" = "LE_wpl",
               "H2O mean concentration (g/m3)" = "H2O_Avg"))
```
**17 Dec 20: When implementing range filter, missing values get connected by a line. :/**
```{r, echo=FALSE, warning=FALSE, message=FALSE}
 numericInput("range_flux_max","Max range of flux graph (non-reactive)",
          value = 1)

 numericInput("range_flux_min","Min range of flux graph (non-reactive)",
            value = -1)

 
radioButtons("variable1_2", "Sonic Anemometer variables:",
             c("Ux" = "Ux_Avg",
               "Uy" = "Uy_Avg",
               "Uz" = "Uz_Avg"))

# numericInput("range_sonic_max","Max range of Sonic graph",
   #        value = 30)

# numericInput("range_sonic_min","Min range of Sonic graph",
    #         value =  -30)


radioButtons("variable2", "Biomet variables:",
             c("Air temperature, hmp (C)" = "t_hmp_mean",
               "Air temperature, sonic (C)" = "Ts_mean",
               "Air temperature, fine wire (C)" = "fw_Avg",
               "Atmospheric pressure (kPa)" = "atm_press_mean",
               "Precipitation (mm)" = "precip_Tot",
               "Leaf wetness, 5m (mV)" = "lws_1_Avg",
               "Leaf wetness, shrub (mV)" = "lws_2_Avg",
               "PAR (umol/m2/s)" = "par_Avg",
               "Short Wave IN (W/m2)" = "Rs_upwell_Avg",
               "Short Wave OUT (W/m2)" = "Rs_downwell_Avg",
               "Long Wave IN (W/m2)" = "Rl_upwell_Avg",
               "Long Wave OUT (W/m2)" = "Rl_downwell_Avg",
               "Soil Heat Flux 1 (W/m2)" = "hfp01_1_Avg",
               "Soil Heat Flux 2 (W/m2)" = "hfp01_2_Avg",
               "Soil Heat Flux 3 (W/m2)" = "hfp01_3_Avg",
              "Soil Heat Flux 4 (W/m2)" = "hfp01_4_Avg"))

# numericInput("range_met_max","Max range of Biomet graph",
    #       value = 40)

# numericInput("range_met_min","Min range of Biomet graph",
       #      value = -20)


radioButtons("variable3", "Instrument variables:",
             c("Battery (V)" = "batt_volt_Avg",
               "AGC/signal strength (unitless)" = "agc_Avg",
               "Datalogger Panel Temperature (C)" = "panel_temp_Avg"))

 
```


Column
-------------------------------------------------------------
```{r, echo = FALSE, warning = FALSE, message = FALSE}
# flux plot
  renderPlot({
    c <- flux[date >= input$daterange[[1]] & date <= input$daterange[[2]],.SD,.SDcols=c("date","date_time",input$variable1)]
    
    setnames(c,input$variable1,"selected")
  # can filter for input range here or in ggplot below
  #  c <- c[selected>=input$range_flux_min & selected<=input$range_flux_max,]
    
  # plot_ly(c,x=~date_time,y=~airtemp, type="scatter")},
  # ggplot(c[selected>=input$range_flux_min & selected<=input$range_flux_max,], aes(date_time, selected))+
     ggplot(c, aes(date_time, selected))+
    geom_line()+
    labs(title = "Flux variables", y=input$variable1)+
 theme_bw()})

# sonic plot
renderPlot({
    c <- flux[date >= input$daterange[[1]] & date <= input$daterange[[2]],.SD,.SDcols=c("date","date_time",input$variable1_2)]
  
    setnames(c,input$variable1_2,"selected")
  
  # plot_ly(c,x=~date_time,y=~airtemp, type="scatter")},
  # ggplot(c[selected>=input$range_sonic_min & selected<=input$range_sonic_max,], aes(date_time, selected))+
   ggplot(c, aes(date_time, selected))+
     geom_line()+
    labs(title = "Sonic Anemomemter Orthogonal Wind Directions x, y, z", y=input$variable1_2)+
 theme_bw()})

# biomet variable plot
renderPlot({
    c <- flux[date >= input$daterange[[1]] & date <= input$daterange[[2]],.SD,.SDcols=c("date","date_time",input$variable2)]
  
    setnames(c,input$variable2,"selected")
  
  # plot_ly(c,x=~date_time,y=~airtemp, type="scatter")},
  # ggplot(c[selected>=input$range_met_min & selected<=input$range_met_max,], aes(date_time, selected))+
   ggplot(c, aes(date_time, selected))+
     geom_line()+
    labs(title = "Biomet variables", y=input$variable2)+
 theme_bw()})

# diagnostics plot
renderPlot({
    c <- flux[date >= input$daterange[[1]] & date <= input$daterange[[2]],.SD,.SDcols=c("date","date_time",input$variable3)]
  
    setnames(c,input$variable3,"selected")
  
  # plot_ly(c,x=~date_time,y=~airtemp, type="scatter")},
  ggplot(c, aes(date_time, selected))+
    geom_line()+
    labs(title = "Instrument variables", y=input$variable3)+
 theme_bw()})
```


# Show Windroses {data-orientation=rows}

Row {data-height=75}
-------------------------------------------------------------
Select Date Range for Wind Rose
```{r, echo=FALSE, warning=FALSE, message=FALSE}

dateRangeInput("daterange2", "Date range:",
                 start = min(flux$date),
                 end   = max(flux$date),
                 min = min(flux$date),
                 max = max(flux$date))

```

Row {data-height=450}
-------------------------------------------------------------
Wind Roses in Compass direction
```{r, echo = FALSE, warning = FALSE, message = FALSE}
# Wind direction from Sonic Anemometer
 renderPlot({
 wind.data <-  flux %>%
   filter((date >= input$daterange2[[1]] & date <= input$daterange2[[2]])) 
 # plot wind variables in windrose
   plot.windrose(wind.data,wind.data$wnd_spd,wind.data$wnd_dir_compass)+
   labs(title="Sonic Anemometer")
 })

renderPlot({
wind.data <-  flux %>%
 filter((date >= input$daterange2[[1]] & date <= input$daterange2[[2]]))
# plot wind variables in windrose
  plot.windrose(wind.data,wind.data$hor_wnd_spd_mean_rslt,wind.data$hor_wnd_dir_mean_rslt)+
  labs(title="2-D Anemometer")
})

```

Row {data-height=250}
-------------------------------------------------------------
Correlation between Sonic and 2-D Anemometer Measurements
```{r, echo=FALSE, warning=FALSE, message=FALSE}
# Wind Speed
renderPlot({
 wind.data <-  flux %>%
   filter((date >= input$daterange2[[1]] & date <= input$daterange2[[2]])) 
 # Wind Direction from Sonic and 2-D
 ggplot(wind.data, aes(wnd_dir_compass,hor_wnd_dir_mean_rslt))+
   geom_point()+
   geom_abline(intercept=0,slope=1)+
   labs(x="Sonic Wind Direction",y="2-D Wind Direction", title="Wind Speed Comparison")
})

# Wind direction
renderPlot({
 wind.data <-  flux %>%
   filter((date >= input$daterange2[[1]] & date <= input$daterange2[[2]])) 
 # Wind Direction from Sonic and 2-D
 ggplot(wind.data, aes(wnd_spd,hor_wnd_spd_mean_rslt))+
   geom_point()+
   geom_abline(intercept=0,slope=1)+
   labs(x="Sonic Wind Speed (compass)",y="2-D Wind Speed", title="Wind Direction Comparison")
})
```

# Tower Soil Moisture Profile and Met Data

Column {.sidebar}
---------------------------------------

###Select Date Range and variables

<!-- #### Last timestamp when data sent to server: -->

<!-- ```{r, echo=FALSE, warning=FALSE, message=FALSE} -->

<!-- print(max(flux$TIMESTAMP)) -->
<!-- ``` -->


<!-- ```{r, echo=FALSE, warning=FALSE, message=FALSE} -->

<!-- dateRangeInput("daterange", "Date range:", -->
<!--                  start = min(flux$date), -->
<!--                  end   = max(flux$date), -->
<!--                  min = min(flux$date), -->
<!--                  max = max(flux$date)) -->


<!-- radioButtons("variable1_1", "Biomet variables:", -->
<!--              c("Air temperature, hmp (C)" = "t_hmp_mean", -->
<!--                "Air temperature, sonic (C)" = "Ts_mean", -->
<!--                "Air temperature, fine wire (C)" = "fw_Avg", -->
<!--                "Atmospheric pressure (kPa)" = "atm_press_mean", -->
<!--                "Precipitation (mm)" = "precip_Tot", -->
<!--                "Leaf wetness, 5m (mV)" = "lws_1_Avg", -->
<!--                "Leaf wetness, shrub (mV)" = "lws_2_Avg", -->
<!--                "PAR (umol/m2/s)" = "par_Avg", -->
<!--                "Short Wave IN (W/m2)" = "Rs_upwell_Avg", -->
<!--                "Short Wave OUT (W/m2)" = "Rs_downwell_Avg", -->
<!--                "Long Wave IN (W/m2)" = "Rl_upwell_Avg", -->
<!--                "Long Wave OUT (W/m2)" = "Rl_downwell_Avg", -->
<!--                "Soil Heat Flux 1 (W/m2)" = "hfp01_1_Avg", -->
<!--                "Soil Heat Flux 2 (W/m2)" = "hfp01_2_Avg", -->
<!--                "Soil Heat Flux 3 (W/m2)" = "hfp01_3_Avg", -->
<!--               "Soil Heat Flux 4 (W/m2)" = "hfp01_4_Avg")) -->


<!-- radioButtons("variable2_1", "Soil Variables:", -->
<!--              c()) -->

<!-- radioButtons("variable3_1", "Instrument variables:", -->
<!--              c("Battery (V)" = "batt_volt_Avg", -->
<!--                "AGC/signal strength (unitless)" = "agc_Avg", -->
<!--                "Datalogger Panel Temperature (C)" = "panel_temp_Avg")) -->


<!-- ``` -->
